services:
  database:
    image: mysql:8.0
    container_name: feishu-github-probot-database
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - glb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${GLB_DB_PASSWORD}
      - MYSQL_DATABASE=${GLB_DB}
    ports:
      - 3306:3306

volumes:
  glb-data: