name: build

on:
  push:
    branches: [master]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  APP_NAME: feishu-github-probot

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ steps.tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest
          secrets: |
            "GLB_PORT=3000"
            "GLB_USERNAME=${{ secrets.GLB_USERNAME }}"
            "GLB_PERSONAL_ACCESS_TOKEN=${{ secrets.GLB_PERSONAL_ACCESS_TOKEN }}"
            "GLB_BASE_URL=${{ secrets.GLB_BASE_URL }}"
            "GLB_APP_ID=${{ secrets.GLB_APP_ID }}"
            "GLB_APP_SECRET=${{ secrets.GLB_APP_SECRET }}"
            "GLB_BOT_OPEN_ID=${{ secrets.GLB_BOT_OPEN_ID }}"
